<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44431" started-at="2014-10-27T11:46:00Z" finished-at="2014-10-27T11:46:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44431" started-at="2014-10-27T11:46:00Z" finished-at="2014-10-27T11:46:44Z">
      <class name="InstabeatSanity.Tests.SanityTestNG">
        <test-method status="PASS" signature="BeforeTests()[pri:0, instance:InstabeatSanity.Tests.SanityTestNG@6debcae2]" name="BeforeTests" is-config="true" duration-ms="21162" started-at="2014-10-27T13:46:00Z" finished-at="2014-10-27T13:46:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTests -->
        <test-method status="FAIL" signature="ValidateValuesInFooter()[pri:0, instance:InstabeatSanity.Tests.SanityTestNG@6debcae2]" name="ValidateValuesInFooter" duration-ms="22205" started-at="2014-10-27T13:46:21Z" finished-at="2014-10-27T13:46:43Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<984> but was:<981>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<984> but was:<981>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at instabeat.dashboard.HomePage.chheckIfTotalDistanceIsProper(HomePage.java:150)
	at InstabeatSanity.Tests.SanityTestNG.ValidateValuesInFooter(SanityTestNG.java:527)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateValuesInFooter -->
        <test-method status="PASS" signature="AfterTests()[pri:0, instance:InstabeatSanity.Tests.SanityTestNG@6debcae2]" name="AfterTests" is-config="true" duration-ms="1056" started-at="2014-10-27T13:46:43Z" finished-at="2014-10-27T13:46:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTests -->
      </class> <!-- InstabeatSanity.Tests.SanityTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
